version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/front
      - /front/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgresql://username:password@db:5432/database
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database"]
      interval: 5s
      timeout: 5s
      retries: 5
